### PR TITLE
docs: add image

### PR DESCRIPTION
**Pull request by PayenThibaud**

### CODE REVIEW

**Review by Bip2311 — CHANGES_REQUESTED** [review]
the coventions is not good

**Review by RemiDebruyne — CHANGES_REQUESTED** [review]
Commit doesnt respect naming convention

**Review by Bip2311 — APPROVED** [review]
covention is okay

**Review by mastemm — APPROVED** [review]
ok for me

**Review by RemiDebruyne — APPROVED** [review]

**Pull request merged**
